# Generated by Django 4.2.7 on 2023-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDR',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('calling_number', models.CharField(max_length=16)),
                ('called_number', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('call_status', models.CharField(max_length=20)),
                ('call_type', models.CharField(max_length=20)),
            ],
        ),
    ]
